name: kuriosity
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2 
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2
  linkify: ^5.0.0
  flutter_linkify: ^6.0.0
  any_link_preview: ^3.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  emoji_picker_flutter: ^4.3.0
  image_picker: ^1.1.2 
  metadata_fetch: ^0.4.2
  http: ^1.4.0
  country_picker: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
